"""add module position constraint

Revision ID: 144f28a9367b
Revises: 16e316eb59b5
Create Date: 2026-09-13 15:11:37.118312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144f28a9367b'
down_revision: Union[str, Sequence[str], None] = '16e316eb59b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_module_course_position', 'modules', ['course_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_module_course_position', 'modules', type_='unique')
    # ### end Alembic commands ###
